spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/mon_projet?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=yasmine
spring.datasource.password=yasmine123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false