-- Baseline du schéma MCL — généré depuis les entités JPA (Hibernate) le 10/09/2026.
-- Représente l'état du schéma à l'introduction de Flyway.
SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE `articles_attente` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `date_ajout` varchar(255) DEFAULT NULL,
  `designation` varchar(255) DEFAULT NULL,
  `marque` varchar(255) DEFAULT NULL,
  `nom_fournisseur` varchar(255) DEFAULT NULL,
  `quantite` int(11) DEFAULT NULL,
  `ref_fournisseur` varchar(255) DEFAULT NULL,
  `refmcl` varchar(255) DEFAULT NULL,
  `utilisateur_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `categories_taches` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `nom` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `clients` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `actif` bit(1) DEFAULT NULL,
  `adresse` varchar(255) DEFAULT NULL,
  `code_client` varchar(255) DEFAULT NULL,
  `contact` varchar(255) DEFAULT NULL,
  `date_desactivation` varchar(255) DEFAULT NULL,
  `desactive_par` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `interlocuteur_achat` varchar(255) DEFAULT NULL,
  `interlocuteur_autres` varchar(255) DEFAULT NULL,
  `interlocuteur_commercial` varchar(255) DEFAULT NULL,
  `interlocuteur_facture` varchar(255) DEFAULT NULL,
  `nom` varchar(255) DEFAULT NULL,
  `responsable_commercial` varchar(255) DEFAULT NULL,
  `type_client` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `commandes` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `date_creation` datetime(6) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `fournisseur` varchar(255) DEFAULT NULL,
  `montant` double DEFAULT NULL,
  `numero` varchar(255) DEFAULT NULL,
  `statut` varchar(255) DEFAULT NULL,
  `utilisateur_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK394iuksyq22ka7rwo7pynmwam` (`utilisateur_id`),
  CONSTRAINT `FK394iuksyq22ka7rwo7pynmwam` FOREIGN KEY (`utilisateur_id`) REFERENCES `utilisateurs` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `conges` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `date_debut` date DEFAULT NULL,
  `date_fin` date DEFAULT NULL,
  `jours_depassement` int(11) DEFAULT NULL,
  `motif` varchar(255) DEFAULT NULL,
  `periode` varchar(255) DEFAULT NULL,
  `statut` varchar(255) DEFAULT NULL,
  `type` varchar(255) DEFAULT NULL,
  `valide_par` varchar(255) DEFAULT NULL,
  `valide_par_kia` bit(1) DEFAULT NULL,
  `utilisateur_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FKm4lj8mg16xddk6jlbn1y227jb` (`utilisateur_id`),
  CONSTRAINT `FKm4lj8mg16xddk6jlbn1y227jb` FOREIGN KEY (`utilisateur_id`) REFERENCES `utilisateurs` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `demandes_approvisionnement` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `code_affaire` varchar(255) DEFAULT NULL,
  `commande_client_recue` varchar(255) DEFAULT NULL,
  `commentaires` varchar(255) DEFAULT NULL,
  `date_attendue` varchar(255) DEFAULT NULL,
  `date_creation` varchar(255) DEFAULT NULL,
  `date_soumission` datetime(6) DEFAULT NULL,
  `date_traitement` varchar(255) DEFAULT NULL,
  `demandeur` varchar(255) DEFAULT NULL,
  `demandeur_id` bigint(20) DEFAULT NULL,
  `department` varchar(255) DEFAULT NULL,
  `devis_file_json` varchar(255) DEFAULT NULL,
  `lignes_json` longtext DEFAULT NULL,
  `montant_total` varchar(255) DEFAULT NULL,
  `nom_projet` varchar(255) DEFAULT NULL,
  `numero` varchar(255) DEFAULT NULL,
  `quotations_obtenues` varchar(255) DEFAULT NULL,
  `responsable_projet` varchar(255) DEFAULT NULL,
  `statut` varchar(255) DEFAULT NULL,
  `traite_par` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `fiches_intervention` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `adresse` varchar(255) DEFAULT NULL,
  `approuve_par` varchar(255) DEFAULT NULL,
  `client` varchar(255) DEFAULT NULL,
  `confirme_par_kia` varchar(255) DEFAULT NULL,
  `contact` varchar(255) DEFAULT NULL,
  `date_approbation` varchar(255) DEFAULT NULL,
  `date_completion` varchar(255) DEFAULT NULL,
  `date_confirmation_kia` varchar(255) DEFAULT NULL,
  `date_creation` datetime(6) DEFAULT NULL,
  `date_fin` date DEFAULT NULL,
  `date_intervention` date DEFAULT NULL,
  `description` text DEFAULT NULL,
  `documents_importes` longtext DEFAULT NULL,
  `heure_debut` varchar(255) DEFAULT NULL,
  `heure_fin` varchar(255) DEFAULT NULL,
  `intervenants` varchar(255) DEFAULT NULL,
  `materiels_hors_standard` text DEFAULT NULL,
  `nom_client_signe` varchar(255) DEFAULT NULL,
  `nom_contact_site` varchar(255) DEFAULT NULL,
  `num_projet` varchar(255) DEFAULT NULL,
  `photos` longtext DEFAULT NULL,
  `signature_client` longtext DEFAULT NULL,
  `signature_technicien` longtext DEFAULT NULL,
  `statut` varchar(255) DEFAULT NULL,
  `taches` longtext DEFAULT NULL,
  `technicien_ids` varchar(255) DEFAULT NULL,
  `technicien_noms` text DEFAULT NULL,
  `tel_contact_site` varchar(255) DEFAULT NULL,
  `manager_id` bigint(20) DEFAULT NULL,
  `technicien_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FKhvcoajtwge4r84otl4tgm24yc` (`manager_id`),
  KEY `FKkobwwdobtx2kfrtwnohc4nbgb` (`technicien_id`),
  CONSTRAINT `FKhvcoajtwge4r84otl4tgm24yc` FOREIGN KEY (`manager_id`) REFERENCES `utilisateurs` (`id`),
  CONSTRAINT `FKkobwwdobtx2kfrtwnohc4nbgb` FOREIGN KEY (`technicien_id`) REFERENCES `utilisateurs` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `journaux_travail` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `date_creation` datetime(6) DEFAULT NULL,
  `date_journee` date DEFAULT NULL,
  `notes_originales` text DEFAULT NULL,
  `rapport_genere` text DEFAULT NULL,
  `signature` longtext DEFAULT NULL,
  `utilisateur_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FKgjmne34bvoy8d57140yrg2bgj` (`utilisateur_id`),
  CONSTRAINT `FKgjmne34bvoy8d57140yrg2bgj` FOREIGN KEY (`utilisateur_id`) REFERENCES `utilisateurs` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `messages_aby` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `contenu` text DEFAULT NULL,
  `date_envoi` datetime(6) DEFAULT NULL,
  `date_reponse` datetime(6) DEFAULT NULL,
  `destinataire` varchar(255) DEFAULT NULL,
  `expediteur` varchar(255) DEFAULT NULL,
  `lu` bit(1) NOT NULL,
  `repondant_nom` varchar(255) DEFAULT NULL,
  `reponse` text DEFAULT NULL,
  `sujet` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `messages_aby_replies` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `auteur` varchar(255) DEFAULT NULL,
  `auteur_role` varchar(255) DEFAULT NULL,
  `contenu` text DEFAULT NULL,
  `date_envoi` datetime(6) DEFAULT NULL,
  `message_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FKfrsusbxldqvack7qefosd35uk` (`message_id`),
  CONSTRAINT `FKfrsusbxldqvack7qefosd35uk` FOREIGN KEY (`message_id`) REFERENCES `messages_aby` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `minutes_securite` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `competences_habilitations` bit(1) DEFAULT NULL,
  `date_creation` datetime(6) DEFAULT NULL,
  `environnement_securise` bit(1) DEFAULT NULL,
  `mesure_prevention_immediate` text DEFAULT NULL,
  `mode_operatoire` bit(1) DEFAULT NULL,
  `nom_signataire` varchar(255) DEFAULT NULL,
  `outils_equipements` bit(1) DEFAULT NULL,
  `risques_specifiques` text DEFAULT NULL,
  `sait_quoi_faire_urgence` bit(1) DEFAULT NULL,
  `signature` varchar(255) DEFAULT NULL,
  `statut` varchar(255) DEFAULT NULL,
  `tacheaeffectuer` varchar(255) DEFAULT NULL,
  `technicien_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK4u9dg7pa2tm5nd2bkjft9hx1k` (`technicien_id`),
  CONSTRAINT `FK4u9dg7pa2tm5nd2bkjft9hx1k` FOREIGN KEY (`technicien_id`) REFERENCES `utilisateurs` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `mises_au_travail` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `chantier_zone` varchar(255) DEFAULT NULL,
  `co_activite_identifiee` bit(1) DEFAULT NULL,
  `co_activite_precision` varchar(255) DEFAULT NULL,
  `date` varchar(255) DEFAULT NULL,
  `date_creation` datetime(6) DEFAULT NULL,
  `description_activite` text DEFAULT NULL,
  `entreprises_intervenantes` varchar(255) DEFAULT NULL,
  `epi_specifiques` bit(1) DEFAULT NULL,
  `evacuation` bit(1) DEFAULT NULL,
  `heure` varchar(255) DEFAULT NULL,
  `modes_operatoires_valides` bit(1) DEFAULT NULL,
  `moyens_alerte` bit(1) DEFAULT NULL,
  `nomsst` varchar(255) DEFAULT NULL,
  `numero` varchar(255) DEFAULT NULL,
  `permis_specifiques` bit(1) DEFAULT NULL,
  `permis_specifiques_precision` varchar(255) DEFAULT NULL,
  `protections_collectives` bit(1) DEFAULT NULL,
  `responsable_intervention` varchar(255) DEFAULT NULL,
  `risques_environnement` bit(1) DEFAULT NULL,
  `risques_tache` bit(1) DEFAULT NULL,
  `secours` bit(1) DEFAULT NULL,
  `statut` varchar(255) DEFAULT NULL,
  `cree_par_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FKc3my07ar9232kic3fej6ouda0` (`cree_par_id`),
  CONSTRAINT `FKc3my07ar9232kic3fej6ouda0` FOREIGN KEY (`cree_par_id`) REFERENCES `utilisateurs` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `options_taches` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `nom` varchar(255) DEFAULT NULL,
  `categorie_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FKhy1gk7awcvxjn44guf6rr7j10` (`categorie_id`),
  CONSTRAINT `FKhy1gk7awcvxjn44guf6rr7j10` FOREIGN KEY (`categorie_id`) REFERENCES `categories_taches` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `planning_notes` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `date` date DEFAULT NULL,
  `note` text DEFAULT NULL,
  `utilisateur_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK7nbchshianlc4disg9p3dobne` (`utilisateur_id`),
  CONSTRAINT `FK7nbchshianlc4disg9p3dobne` FOREIGN KEY (`utilisateur_id`) REFERENCES `utilisateurs` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `reclamations_sse` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `action_corrective` text DEFAULT NULL,
  `analyse_causes` text DEFAULT NULL,
  `date` varchar(255) DEFAULT NULL,
  `date_creation` datetime(6) DEFAULT NULL,
  `description_faits` text DEFAULT NULL,
  `echeance` varchar(255) DEFAULT NULL,
  `entreprise_concernee` varchar(255) DEFAULT NULL,
  `gravite` varchar(255) DEFAULT NULL,
  `heure` varchar(255) DEFAULT NULL,
  `information_declarant` bit(1) DEFAULT NULL,
  `lieu` varchar(255) DEFAULT NULL,
  `mesure_immediate` text DEFAULT NULL,
  `numero` varchar(255) DEFAULT NULL,
  `photos_json` longtext DEFAULT NULL,
  `responsable_action` varchar(255) DEFAULT NULL,
  `statut` varchar(255) DEFAULT NULL,
  `type_presqu_accident` bit(1) DEFAULT NULL,
  `type_situation_dangereuse` bit(1) DEFAULT NULL,
  `type_suggestion` bit(1) DEFAULT NULL,
  `technicien_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK7e1tj5q7cfn3r1534cb3m8c6b` (`technicien_id`),
  CONSTRAINT `FK7e1tj5q7cfn3r1534cb3m8c6b` FOREIGN KEY (`technicien_id`) REFERENCES `utilisateurs` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `reset_password_requests` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `datedemande` varchar(255) DEFAULT NULL,
  `statut` varchar(255) DEFAULT NULL,
  `username` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `stock` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `categorie` varchar(255) DEFAULT NULL,
  `date_creation` datetime(6) DEFAULT NULL,
  `date_maj` datetime(6) DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `fournisseur` varchar(255) DEFAULT NULL,
  `nom` varchar(255) DEFAULT NULL,
  `prix_unitaire` double DEFAULT NULL,
  `quantite` int(11) DEFAULT NULL,
  `reference` varchar(255) DEFAULT NULL,
  `utilisateur_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK2pddt25nlde8twlqvhiw4mhup` (`utilisateur_id`),
  CONSTRAINT `FK2pddt25nlde8twlqvhiw4mhup` FOREIGN KEY (`utilisateur_id`) REFERENCES `utilisateurs` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `taches` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `adresse` varchar(255) DEFAULT NULL,
  `assignes` text DEFAULT NULL,
  `ca_devis` varchar(255) DEFAULT NULL,
  `chiffre_affaire` varchar(255) DEFAULT NULL,
  `client` varchar(255) DEFAULT NULL,
  `client_final` varchar(255) DEFAULT NULL,
  `date_creation` datetime(6) DEFAULT NULL,
  `date_echeance` date DEFAULT NULL,
  `description` text DEFAULT NULL,
  `etapes` text DEFAULT NULL,
  `fichiers` longtext DEFAULT NULL,
  `num_devis` varchar(255) DEFAULT NULL,
  `priorite` varchar(255) DEFAULT NULL,
  `statut` varchar(255) DEFAULT NULL,
  `titre` varchar(255) DEFAULT NULL,
  `utilisateur_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FKr6bwr1pa82wf1c4c800txf4py` (`utilisateur_id`),
  CONSTRAINT `FKr6bwr1pa82wf1c4c800txf4py` FOREIGN KEY (`utilisateur_id`) REFERENCES `utilisateurs` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `tickets` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `criticite` varchar(255) DEFAULT NULL,
  `date_creation` datetime(6) DEFAULT NULL,
  `date_validation` datetime(6) DEFAULT NULL,
  `description_panne` text DEFAULT NULL,
  `echeance` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `etage` varchar(255) DEFAULT NULL,
  `informations_additionnelles` text DEFAULT NULL,
  `lieu_site` varchar(255) DEFAULT NULL,
  `marque` varchar(255) DEFAULT NULL,
  `nom` varchar(255) DEFAULT NULL,
  `nom_salle` varchar(255) DEFAULT NULL,
  `numero` varchar(255) DEFAULT NULL,
  `prenom` varchar(255) DEFAULT NULL,
  `priorite` varchar(255) DEFAULT NULL,
  `reference` varchar(255) DEFAULT NULL,
  `site` varchar(255) DEFAULT NULL,
  `sous_garantie` bit(1) DEFAULT NULL,
  `statut` varchar(255) DEFAULT NULL,
  `telephone` varchar(255) DEFAULT NULL,
  `type_materiel` varchar(255) DEFAULT NULL,
  `validee_par` varchar(255) DEFAULT NULL,
  `assigne_id` bigint(20) DEFAULT NULL,
  `demandeur_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK33rni60eg1efbunifvfvugty1` (`assigne_id`),
  KEY `FK636hlx4x0r98fh317cr671nef` (`demandeur_id`),
  CONSTRAINT `FK33rni60eg1efbunifvfvugty1` FOREIGN KEY (`assigne_id`) REFERENCES `utilisateurs` (`id`),
  CONSTRAINT `FK636hlx4x0r98fh317cr671nef` FOREIGN KEY (`demandeur_id`) REFERENCES `utilisateurs` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `utilisateurs` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `actif` bit(1) DEFAULT NULL,
  `date_desactivation` varchar(255) DEFAULT NULL,
  `date_embauche` date DEFAULT NULL,
  `departement` varchar(255) DEFAULT NULL,
  `desactive_par` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `nom` varchar(255) DEFAULT NULL,
  `password` varchar(255) DEFAULT NULL,
  `poste` varchar(255) DEFAULT NULL,
  `premier_connexion` bit(1) NOT NULL,
  `prenom` varchar(255) DEFAULT NULL,
  `role` varchar(255) DEFAULT NULL,
  `statut` varchar(255) DEFAULT NULL,
  `telephone` varchar(255) DEFAULT NULL,
  `username` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `visiteurs` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `date_ajout` datetime(6) DEFAULT NULL,
  `nom` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `voitures` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `annee` varchar(255) DEFAULT NULL,
  `assurance` varchar(255) DEFAULT NULL,
  `carburant` varchar(255) DEFAULT NULL,
  `conducteur` varchar(255) DEFAULT NULL,
  `date_expiration_assurance` date DEFAULT NULL,
  `immatriculation` varchar(255) DEFAULT NULL,
  `kilometrage` varchar(255) DEFAULT NULL,
  `marque` varchar(255) DEFAULT NULL,
  `modele` varchar(255) DEFAULT NULL,
  `prochain_controle` date DEFAULT NULL,
  `statut` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS=1;
